# 使用github actions部署example 
# 工作流很像是剧本，on是什么时候，jobs是干什么事情，jobs是可以多个同时进行，每个job都可以有多个步骤，步骤是按顺序执行的
# 工作流名称
on: push
jobs:
  job1:
    # 告诉github使用的服务器环境
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello, world!"
    - run: pwd
  job2:
    runs-on: windows-latest
    steps:
    - run: node --version